### PR TITLE
[WIP] Shushman/0.7 fixes

### PR DESCRIPTION
**Pull request by Shushman**
Updates to notebook files as well as included Julia files. @mykelk please `dev` the appropriate dependencies one by one and checkout the correct branch for it to work. Some errors that you may want to try and recreate
- Notebook 10 works syntactically but has some output formatting issues
- Notebook 11 is having an issue with the `plot` function at the end - `pdf2svg error`
- Notebook 16 depends on an updated POMCP solver - is someone doing that? @zsunberg

### CODE REVIEW

**Comment by zsunberg** [comment]
@Shushman Yeah the POMCP solver is a little ways down the line, but I am working towards it

**Comment by Shushman** [comment]
@zsunberg so as of now, notebooks 1-11 all work on my machine with the packages installed separately by me.
Notebook 12-15 are empty, while 16 depends on `POMCP` and `LaserTag`. Assuming I fix the syntactical errors with them, how should `install.jl` and `.travis.yml` be changed?

**Comment by Shushman** [comment]
Also @zsunberg can I delegate the fixing of notebook 16 to you? I've fixed the obvious syntactical errors but I am getting some more involved errors in the lower half (where `LaserTag` is used), such as `support` not being defined for `LaserTag` and in its interaction with `ParticleFilters`, and `stringmime` usage with `HTML`

**Comment by Shushman** [comment]
Merging but rendering needs to be fixed for 8 onwards @dressel

**Pull request merged**
